### PR TITLE
Added Sticky portion

### PR DESCRIPTION
**Pull request by tannishk**
Kindly see and make the necessary changes and commit

### CODE REVIEW

**Comment by handasolo** [comment]
I don't know why you didn't push to your previous PR. I guess, I'll have to close that.

**Comment by handasolo** [comment]
Your origin is running 25 commits behind upstream, please update. And, I'm facing a lot of glitches. Let's see if your origin update fixes that.

**Comment by tannishk** [comment]
Do i have to rebase my local branch for this ?

**Comment by MozillaDelhi** [comment]
@tannishk  Please get your pull request merged asap.

**Comment by tannishk** [comment]
@Slayslot did you check this ?

**Comment by handasolo** [comment]
@tannishk Yes, this will require some work to be production level ready so I'm pushing this for after the website goes live.

**Comment by CuriousLearner** [comment]
@Slayslot, since this breaks the site as tested today, let's close this down. What's your take on this?

**Comment by handasolo** [comment]
@CuriousLearner Sounds like a plan. @tannishk if you'd like to start working again, let us know.

**Comment by CuriousLearner** [comment]
Closing this. @tannishk If you want to do this, re-open this.

**Pull request closed without merging**
