### PR TITLE
send button alignment and footer overflow fixed 

### PR DESCRIPTION
**Pull request by deepakpathania-zz**
I can't seem to find why I have two commits when I have made only one. The first one is simply about merging the develop which I guess was added when I pulled the changes in the develop branch to stay in sync. Since that stages the pull request you have already merged, I guess you can **finally** merge this PR based on the commit I have made :)

### CODE REVIEW

**Comment by handasolo** [comment]
@deepakpathania Please set your name and email on your git. Even if, for some reason, you don't like to use your name, at least add your email. It helps us know who committed a particular piece of code. Letting this one slide.

**Comment by CuriousLearner** [comment]
@Slayslot This shouldn't have been done 😔

**Comment by deepakpathania-zz** [comment]
@Slayslot Sure,  I'll do that. @CuriousLearner Is there anything I did wrong ?  I am a beginner at open source contributions and very receptive to suggestions and advices. Please let me know what went wrong according to you and I'll keep that in mind from now on.

**Comment by CuriousLearner** [comment]
@deepakpathania Please set up your configuration file in git.

Secondly, there are two commits, because you didn't have the latest pull of the develop branch, and you committed your work. So essentially when you had to re-base, you tried to pull the latest code, for which git automatically merged your code with the latest code in the develop branch, and hence the second commit.

We all are learning from our mistakes. Please take a look at these:

http://www.git-scm.com
https://www.atlassian.com/git/tutorials/

**Comment by deepakpathania-zz** [comment]
@CuriousLearner Yeah. I pulled the contents of the master branch instead of develop, I guess. That is why I had all that trouble in rebasing and squashing my commits. Thanks for the references. I'll try not to screw up like this next time. Really embarrassed. 😔

**Comment by CuriousLearner** [comment]
If you really don't want to rebase and squash, then better is to use git stash and then take latest pull. Then do git stash pop, resolve conflicts if any and once you're done, commit your work.

**Comment by deepakpathania-zz** [comment]
Sounds cool. Would keep in mind for my future contributions. Thanks :smile:

**Comment by deepakpathania** [comment]
@Slayslot @CuriousLearner  Have you not merged my first commit ? The one with the message "send and footer overflow fixed". Please merge that as well since that has all the changes I made.

**Pull request merged**
