### PR TITLE
Contact form added.Made suggested changes. Resolved merge conflicts.

### PR DESCRIPTION
**Pull request by manrajgrover**
Please review.

### CODE REVIEW

**Comment by handasolo** [comment]
@ManrajGrover Don't need tel and subject.

**Comment by MozillaDelhi** [comment]
This is vast :+1:

**Comment by handasolo** [comment]
screen shot 2015-07-03 at 19 09 22 at pixels 994×471

**Comment by manrajgrover** [comment]
@Slayslot This is a break point between medium and small devices. See http://getbootstrap.com/css/#grid-options

**Comment by handasolo** [comment]
Point was that this usually doesn't happen, but I can't seem to reproduce this any more :|

**Comment by manrajgrover** [comment]
Okay @Slayslot . Then I guess its good to go. @Mozpacers/contributors

**Comment by handasolo** [comment]
Okay from my side. Further styling can be handled by me.

**Pull request merged**
