### PR TITLE
Navbar styling done

### PR DESCRIPTION
**Pull request by askprateek**
Navbar color changed acc. to the official sites.

Removed radius from mobile menu.

### CODE REVIEW

**Comment by handasolo** [comment]
Need more work here than just to change the color.

**Comment by askprateek** [comment]
Please Suggest something.

**Comment by handasolo** [comment]
@askprateek Maybe add the animation that you added to the footer, fix the type a bit, make the tabzilla tab bigger and with it the nav bar bigger. That way we can cover the fold with the navbar and the hero image. I don't know, you don't have to completely follow what I ask, this is the styling phase, just be more creativity than changing the color of the hyperlinks.

**Comment by askprateek** [comment]
Check this @Slayslot

**Comment by handasolo** [comment]
@askprateek Love the hover. Please update your fork and squash these commits.

**Comment by askprateek** [comment]
Okhe

**Comment by askprateek** [comment]
@Slayslot Please Merge it now.

**Comment by handasolo** [comment]
@askprateek Need those commits squashed, as I mentioned.

**Comment by CuriousLearner** [comment]
@askprateek Are you still on this? Please update us about this.

**Comment by CuriousLearner** [comment]
I'm closing this, since haven't heard from a lot of time. If you still want to do it, please considering re-opening this. @askprateek 
cc @Slayslot

**Pull request closed without merging**
