### PR TITLE
Hero Image

### PR DESCRIPTION
**Pull request by askprateek**
Hero Image Added with Simple Animation 
screenshot 78

### CODE REVIEW

**Comment by handasolo** [comment]
Won't fit the entire page?

**Comment by anupkumarmishra** [comment]
Sorry can't approve this . It should be on the full page . Do we have separate plans for the remaining parts of the page ?

**Comment by handasolo** [comment]
@anupkumarmishra Whatever do you mean by separate plans?

**Comment by anupkumarmishra** [comment]
@Slayslot  The way image is fitting to the page doesn't gives a good view. It should be extended to the whole page  , why are we leaving margins ?

**Comment by CuriousLearner** [comment]
@askprateek Make the width to fit the container, it should fill in the entire space. Please make these changes and update us on this PR.

**Comment by manrajgrover** [comment]
Some members are missing as well. :|

**Comment by handasolo** [comment]
@ManrajGrover Haha

**Comment by askprateek** [comment]
Acc.to me Height is Perfect, It shows our community pic and About us Section. I will try to do something of the Width. XD

**Comment by handasolo** [comment]
Closing this. Make another one when you push the changes.

**Pull request closed without merging**
