### PR TITLE
send button alignment and footer overflow fixed 

### PR DESCRIPTION
**Pull request by deepakpathania-zz**
Solves the issue of strange behaviour of send button in terms of alignment on different screen sizes and footer overflow on mobile.

### CODE REVIEW

**Comment by deepakpathania-zz** [comment]
Resolves #63  #64

**Comment by handasolo** [comment]
Can't seem to understand what you're trying to do with the indentation here. And, I still see two commits when it should be one squashed commit.

**Comment by deepakpathania-zz** [comment]
I just re indented the code to look better on my local copy, pushed the same one. My bad. I'll make a new PR, really sorry for all this hustle over a single bug, kinda new to this.

**Comment by handasolo** [comment]
@deepakpathania That's alright. Everyone has to start somewhere. Also, you could have made changes, squashed your three commits into one and forced pushed here.

**Comment by deepakpathania-zz** [comment]
I tried squashing the commits but I seem to have some synchronization errors and can neither rebase nor amend because of those, can't figure out the way to do it.

**Comment by CuriousLearner** [comment]
You're not supposed to squash commits, once you push them, it would just mess it all up.

**Pull request closed without merging**
