### PR TITLE
Added basic frontend to the about section

### PR DESCRIPTION
**Pull request by abhijeetchauhan**

### CODE REVIEW

**Comment by CuriousLearner** [comment]
Hi @supernoobabhi Please make your code compatible to the guidelines. Use two spaces indentation for your code.

**Comment by abhijeetchauhan** [comment]
i have used 2 space indentation

**Comment by CuriousLearner** [comment]
@supernoobabhi src/client/index.html
line 72

**Comment by abhijeetchauhan** [comment]
fixed

**Comment by handasolo** [comment]
@supernoobabhi Are those magic numbers in media query?

**Comment by abhijeetchauhan** [comment]
when the about(community) section is less than the no. Of px in width(as in media query) the layout changes from horizontal to vertical.
and for about section the pictures becomes pretty big at that no.  so used small size pictures .
basically it was for responsiveness .

**Comment by handasolo** [comment]
I don't see how your first media query is making any difference. And the second and third ones are fine but the break happens on a magic number. It shouldn't happen there. Refer to http://getbootstrap.com/css/#grid-options. This is where most of your breaks should happen if you're incorporating bootstrap in the correct way. There can be exceptions but there should be a reason for those exceptions, they shouldn't be magic numbers.

**Pull request merged**
