### PR TITLE
Ajax Loader Image For Contact Us Form Added And #43 fixed

### PR DESCRIPTION
**Pull request by vipinkhushu**
Now people with slow connections will be able to know that their request is under processing and they need not press submit button again and again

### CODE REVIEW

**Comment by handasolo** [comment]
Looks good to me just center the gif on the button. Also, add the fix for Issue #43 in this PR as discussed and squash all the commits into one.

**Comment by handasolo** [comment]
Kindly find some other fix for #43, I'm officially assigning it to you. Also, [squash your commits](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Squashing-Commits) and then [update your fork](https://help.github.com/articles/syncing-a-fork/) before moving further. And, I asked you to center the loading gif on the button.

**Comment by CuriousLearner** [comment]
@vipinkhushu waiting for your update on this.

**Comment by vipinkhushu** [comment]
Will submit PR today

**Comment by CuriousLearner** [comment]
@vipinkhushu Just update this one with your latest work. You can use force push on your fork.

**Comment by vipinkhushu** [comment]
check now

**Comment by CuriousLearner** [comment]
@vipinkhushu It is conflicting, can you please resolve the conflicts? and squash your commits when you're done.

**Comment by vipinkhushu** [comment]
okey! working on it

**Pull request closed without merging**
