### PR TITLE
Contact Form added.

### PR DESCRIPTION
**Pull request by manrajgrover**
Contact form added. Please review and let me know the changes. @anupkumarmishra @Mozpacers/contributors

### CODE REVIEW

**Comment by handasolo** [comment]
@ManrajGrover Use of grid could be better, and you can add checks using focusin focusout, that way the user doesn't have to press the button to get to know that something wrong has been entered in the field. You can disable that button until all fields have been filled. and we don't require subject or number.

**Comment by manrajgrover** [comment]
@Slayslot Please comment on lines. I'm not sure where you find grid missing. Regarding focus in and out, okay. This is strictly according to the wireframe provided to me.

**Comment by handasolo** [comment]
@ManrajGrover Grid is not missing, but it can be made to look better. But, this is good with respect to the wireframe :+1: , maybe we can merge and I can add changes for the looks later. And I did mention to leave out number and subject.

**Comment by CuriousLearner** [comment]
Hi, @ManrajGrover ,all looks good, but please make the contact of contact type of tel type and not text.

**Pull request closed without merging**
