### PR TITLE
Color scheme and Typographic changes

### PR DESCRIPTION
**Pull request by h4xr**
Some changes made to color scheme and text styling
1). Styling of links in the masthead
2). Changed background color of About Us section
3). Text alignment in about us section

### CODE REVIEW

**Comment by CuriousLearner** [comment]
@h4xr Thanks for the PR.

The background-color of about us section is red and the section just below that is also a shade of red.

Can we change the color of about us to something else please.

**Comment by h4xr** [comment]
mozilla delhi mozpacers

Does this look good?

**Comment by CuriousLearner** [comment]
Please update the changes as discussed, update your fork and sqash your changes into one commit.

**Comment by h4xr** [comment]
@CuriousLearner Changes done and squashed.
Please take a look.

**Comment by CuriousLearner** [comment]
Awesome! Merging in :)

**Pull request merged**
