### PR TITLE
Color scheme and typography changes

### PR DESCRIPTION
**Pull request by h4xr**
Fixed the merge conflict. Changes to the color scheme and typography.

### CODE REVIEW

**Comment by handasolo** [comment]
@h4xr You're running behind develop.

**Comment by CuriousLearner** [comment]
@h4xr Right now it's breaking the events section. Please rectify that.

**Comment by h4xr** [comment]
@CuriousLearner The code didn't modify anything in the events section. Might be some other issue.

**Comment by handasolo** [comment]
@h4xr Again it's because you're running behind. Please [sync your fork](https://help.github.com/articles/syncing-a-fork/).

**Pull request closed without merging**
