### PR TITLE
Contact form added

### PR DESCRIPTION
**Pull request by manrajgrover**
Please review and let me know the changes. I have tried to use Git-Flow to best of my ability but there were some things that were not clear so let me know if I missed anything. @anupkumarmishra @Mozpacers/contributors

### CODE REVIEW

**Comment by CuriousLearner** [comment]
@ManrajGrover Please put your pull request on develop branch, nothing should be there on master branch. 

secondly, once you're done with your feature finish it. And your feature should be from develop branch.

**Comment by manrajgrover** [comment]
@CuriousLearner Let me know the commands for it as the explanation that I got for the same states that the feature branch gets deleted if I run "git flow feature pull origin MYFEATURE" which I don't want to.

**Comment by CuriousLearner** [comment]
Yes it would, first git pull from this remote so that your fork is at the same position as this repo, change your branch with git checkout develop then make a feature put all your code there and finish it, It would automatically come to develop. Then update your forked remote by git push -u origin develop and then issue a pull request.

To finish a feature do git flow feature end MYFEATURE

**Comment by manrajgrover** [comment]
@CuriousLearner And what if I have changes to push later? The branch would already have been deleted. Now what?

**Comment by CuriousLearner** [comment]
Only your feature branch not the develop branch.

**Comment by anupkumarmishra** [comment]
@CuriousLearner  Please plan a session on Gitflow ASAP. Let's not keep things stuck due to this.

**Pull request closed without merging**
